defaults: &dir
  working_directory: ~/catkin_ws

defaults: &image
  docker:
    - image: robojackets/roboracing-baseimage:latest

defaults: &install_deps
  run: apt-get update && rosdep update && rosdep install -iy --from-paths ./src --skip-keys='realsense2_camera pointgrey_camera_driver libuvc_camera'

defaults: &save_src_cache
  save_cache:
    key: source-v1-{{ .Branch }}-{{ .Revision }}
    paths:
    - ".git"
defaults: &load_src_cache
  restore_cache:
    keys:
    - source-v1-{{ .Branch }}-{{ .Revision }}
    - source-v1-{{ .Branch }}-
    - source-v1-
defaults: &save_compile_cache
  save_cache:
    key: ccache-{{ arch }}-{{ .Branch }}-{{ .Revision }}
    paths:
    - ~/.ccache
defaults: &load_compile_cache
  restore_cache:
    keys:
    - ccache-{{ arch }}-{{ .Branch }}-{{ .Revision }}
    - ccache-{{ arch }}-{{ .Branch }}
    - ccache-{{ arch }}
    - ccache-
defaults: &save_test_cache
  save_cache:
    key: ccache-test-{{ arch }}-{{ .Branch }}-{{ .Revision }}
    paths:
      - ~/.ccache
defaults: &load_test_cache
  restore_cache:
    keys:
      - ccache-test-{{ arch }}-{{ .Branch }}-{{ .Revision }}
      - ccache-test-{{ arch }}-{{ .Branch }}
      - ccache-test-{{ arch }}
      - ccache-test-

defaults: &save_workspace
  persist_to_workspace:
    root: ~/catkin_ws
    paths:
      - build/*
      - devel/*
defaults: &load_workspace
  attach_workspace:
    at: ~/catkin_ws

version: 2
jobs:
  compile:
    <<: *dir
    <<: *image
    steps:
      - <<: *load_src_cache
      - checkout:
          path: ~/catkin_ws/src/roboracing-software
      - <<: *save_src_cache
      - <<: *install_deps
      - <<: *load_compile_cache
      - run: source /opt/ros/melodic/setup.sh && catkin_make -j2
      - <<: *save_compile_cache
      - <<: *save_workspace
  test:
    <<: *dir
    <<: *image
    steps:
      - <<: *load_src_cache
      - checkout:
          path: ~/catkin_ws/src/roboracing-software
      - <<: *save_src_cache
      - <<: *install_deps
      - <<: *load_workspace
      - <<: *load_test_cache
      - run: source /opt/ros/melodic/setup.sh && catkin_make run_tests && catkin_test_results
      - <<: *save_test_cache

workflows:
  version: 2
  build_and_test:
    jobs:
      - compile
      - test:
          requires:
            - compile
