<robot name="rigatoni_opponent" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="use_gpu" value="false"/>

    <xacro:property name="props" value="${load_yaml('../conf/evgp_car_params.yaml')}"/>
    <xacro:property name="body_inertia" value="${props['body_inertia']}"/>

    <!-- ************************** Links *************************** -->
    <xacro:macro name="null_inertia">
        <inertial>
            <mass value="0.0001"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="mesh_geometry">
        <geometry>
            <mesh filename="package://rr_description/meshes/rigatoni.stl" scale="0.01 0.01 0.01"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="set_link_color" params="link color">
        <gazebo reference="${link}">
            <material>Gazebo/${color}</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="evgp_body" params="collision_bitmask color">

        <!-- ************************** Links *************************** -->

        <link name="opponent_base_footprint">
            <xacro:null_inertia/>
        </link>

        <link name="body_visual_origin">
            <xacro:null_inertia/>
            <visual>
                <xacro:mesh_geometry/>
            </visual>
            <!--            <collision>-->
            <!--                <xacro:mesh_geometry/>-->
            <!--            </collision>-->
        </link>
        <xacro:set_link_color link="body_visual_origin" color="${color}"/>
        <gazebo reference="body_visual_origin">
            <collision>
                <surface>
                    <contact>
                        <collide_bitmask>${collision_bitmask}</collide_bitmask>
                    </contact>
                </surface>
            </collision>
        </gazebo>

        <link name="body_inertial_center">
            <inertial>
                <mass value="${props['body_mass']}"/>
                <inertia ixx="${body_inertia[0]}" ixy="${body_inertia[1]}" ixz="${body_inertia[2]}"
                         iyy="${body_inertia[3]}" iyz="${body_inertia[4]}" izz="${body_inertia[5]}"/>
            </inertial>
        </link>
        <gazebo reference="body_inertial_center"/>


        <!-- ************************** Joints *************************** -->

        <joint name="opponent_base_footprint_to_mesh_origin" type="fixed">
            <parent link="opponent_base_footprint"/>
            <child link="body_visual_origin"/>
            <origin xyz="0.53 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        </joint>

        <joint name="opponent_base_footprint_to_body_inertial_center" type="fixed">
            <parent link="opponent_base_footprint"/>
            <child link="body_inertial_center"/>
            <origin xyz="${' '.join(str(x) for x in props['body_com'])}"/>
        </joint>

    </xacro:macro>
    <xacro:evgp_body collision_bitmask="0x1" color="Grey"/>

    <xacro:macro name="wheel_link" params="name radius width">
        <link name="${name}">
            <inertial>
                <mass value="0.01"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0"
                         izz="${0.5 * props['wheel_mass'] * pow(radius, 2)}"/>
            </inertial>
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${width}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${width}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="${name}">
            <mu1>0.7</mu1>
            <mu2>0.7</mu2>
            <kp>1000000</kp>
            <kd>1000000</kd>
            <collision>
                <surface>
                    <contact>
                        <collide_bitmask>0x1</collide_bitmask>
                    </contact>
                </surface>
            </collision>
        </gazebo>
        <xacro:set_link_color link="${name}" color="Black"/>
    </xacro:macro>
    <xacro:wheel_link name="wheel_BL" radius="${props['wheel_radius_back']}" width="${props['wheel_width_back']}"/>
    <xacro:wheel_link name="wheel_BR" radius="${props['wheel_radius_back']}" width="${props['wheel_width_back']}"/>
    <xacro:wheel_link name="wheel_FL" radius="${props['wheel_radius_front']}" width="${props['wheel_width_front']}"/>
    <xacro:wheel_link name="wheel_FR" radius="${props['wheel_radius_front']}" width="${props['wheel_width_front']}"/>

    <link name="steering_link_left">
        <xacro:null_inertia/>
    </link>
    <link name="steering_link_right">
        <xacro:null_inertia/>
    </link>

    <link name="gps_link">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="gps_link" color="Gold"/>

    <link name="camera">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
        <visual>
            <origin rpy="0 ${pi/2} 0" xyz="0.05 0 0"/>
            <geometry>
                <cylinder radius="0.03" length="0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="camera" color="Gold"/>

    <link name="imu_top_link">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="imu_top_link" color="Gold"/>
    <link name="imu_bottom_link">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="imu_bottom_link" color="Gold"/>

    <link name="white">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="white">
        <material>none</material>
    </gazebo>

    <link name="white_back_left">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="white_back_left">
        <material>none</material>
    </gazebo>

    <link name="white_side_left">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="white_side_left">
        <material>none</material>
    </gazebo>

    <link name="white_front_left">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="white_front_left">
        <material>none</material>
    </gazebo>

    <link name="white_front_mid">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="white_front_mid">
        <material>none</material>
    </gazebo>

    <link name="white_front_right">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>

    <link name="white_side_right">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>

    <link name="white_back_right">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>

    <link name="4_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="4_april">
        <material>tag36_11_00004</material>
    </gazebo>

    <link name="5_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="5_april">
        <material>tag36_11_00005</material>
    </gazebo>

    <link name="6_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="6_april">
        <material>tag36_11_00006</material>
    </gazebo>

    <link name="7_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="7_april">
        <material>tag36_11_00007</material>
    </gazebo>

    <link name="0_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="0_april">
        <material>tag36_11_00000</material>
    </gazebo>

    <link name="1_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="1_april">
        <material>tag36_11_00001</material>
    </gazebo>

    <link name="2_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="2_april">
        <material>tag36_11_00002</material>
    </gazebo>

    <link name="3_april">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.001 0.3 0.3 "/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="3_april">
        <material>tag36_11_00003</material>
    </gazebo>

    <!-- ************************** Joints *************************** -->

    <xacro:property name="joint_flop_both" value="0.03"/>
    <xacro:macro name="back_wheel_joint" params="dest_link y">
        <joint name="opponent_base_footprint_to_${dest_link}" type="continuous">
            <parent link="opponent_base_footprint"/>
            <child link="${dest_link}"/>
            <origin xyz="0 ${y} ${(props['wheel_radius_back'] / 2) - joint_flop_both}" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <gazebo reference="opponent_base_footprint_to_${dest_link}"/>
    </xacro:macro>
    <xacro:back_wheel_joint dest_link="wheel_BL" y="${props['track'] / 2}"/>
    <xacro:back_wheel_joint dest_link="wheel_BR" y="${-props['track'] / 2}"/>

    <xacro:property name="joint_flop_front" value="0.007"/>
    <xacro:macro name="steering_joints" params="steering_link wheel_link y">
        <joint name="opponent_base_footprint_to_${steering_link}" type="revolute">
            <parent link="opponent_base_footprint"/>
            <child link="${steering_link}"/>
            <origin xyz="${props['wheelbase']} ${y} ${props['wheel_radius_front'] / 2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="${-props['max_steering']}" upper="${props['max_steering']}" effort="10000.0"
                   velocity="${props['steering_speed']}"/>
        </joint>
        <gazebo reference="opponent_base_footprint_to_${steering_link}"/>

        <joint name="${steering_link}_to_${wheel_link}" type="continuous">
            <origin xyz="0 0 ${-joint_flop_both - joint_flop_front}" rpy="${pi/2} 0 0"/>
            <parent link="${steering_link}"/>
            <child link="${wheel_link}"/>
            <axis xyz="0 0 1"/>
        </joint>
        <gazebo reference="${steering_link}_to_${wheel_link}"/>
    </xacro:macro>
    <xacro:steering_joints steering_link="steering_link_left" wheel_link="wheel_FL" y="${props['track'] / 2}"/>
    <xacro:steering_joints steering_link="steering_link_right" wheel_link="wheel_FR" y="${-props['track'] / 2}"/>

    <joint name="opponent_base_footprint_to_gps" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="gps_link"/>
        <origin xyz="0.63 0.4 1.27" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_camera" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="camera"/>
        <origin xyz="0.68 0.4 0.8" rpy="0 0.2 0"/>
    </joint>

    <xacro:macro name="camera_optical_frame" params="camera_link">
        <link name="${camera_link}_optical">
            <xacro:null_inertia/>
        </link>
        <joint name="${camera_link}_to_optical" type="fixed">
            <parent link="${camera_link}"/>
            <child link="${camera_link}_optical"/>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        </joint>
    </xacro:macro>

    <xacro:camera_optical_frame camera_link="camera"/>

    <joint name="opponent_base_footprint_to_imu" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="imu_top_link"/>
        <origin xyz="0.67 0.4 0.67" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_imu2" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="imu_bottom_link"/>
        <origin xyz="0 0 0.21" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_4_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="4_april"/>
        <origin xyz="-.3 0 0.51" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_back_mid_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white"/>
        <origin xyz="-.29 0 0.51" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_5_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="5_april"/>
        <origin xyz="-.21581 .3937 0.51" rpy="0 0 -${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_back_left_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_back_left"/>
        <origin xyz="-.20581 .3837 0.51" rpy="0 0 -${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_6_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="6_april"/>
        <origin xyz=".512 .45 0.51" rpy="0 0 -${pi/2}"/>
    </joint>

    <joint name="opponent_base_footprint_to_side_left_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_side_left"/>
        <origin xyz=".512 .44 0.51" rpy="0 0 -${pi/2}"/>
    </joint>

    <joint name="opponent_base_footprint_to_7_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="7_april"/>
        <origin xyz="1.2414 .3937 0.51" rpy="0 0 ${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_front_left_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_front_left"/>
        <origin xyz="1.2314 .3837 0.51" rpy="0 0 ${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_0_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="0_april"/>
        <origin xyz="1.3256 0 0.51" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_front_mid_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_front_mid"/>
        <origin xyz="1.3156 0 0.51" rpy="0 0 0"/>
    </joint>

    <joint name="opponent_base_footprint_to_1_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="1_april"/>
        <origin xyz="1.2414 -.3937 0.51" rpy="0 0 -${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_front_right_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_front_right"/>
        <origin xyz="1.2314 -.3837 0.51" rpy="0 0 -${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_2_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="2_april"/>
        <origin xyz=".512 -.3937 0.51" rpy="0 0 -${pi/2}"/>
    </joint>

    <joint name="opponent_base_footprint_to_side_right_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_side_right"/>
        <origin xyz=".512 -.3837 0.51" rpy="0 0 -${pi/2}"/>
    </joint>

    <joint name="opponent_base_footprint_to_3_april" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="3_april"/>
        <origin xyz="-.21581 -.3937 0.51" rpy="0 0 ${pi/4}"/>
    </joint>

    <joint name="opponent_base_footprint_to_back_right_april_white" type="fixed">
        <parent link="opponent_base_footprint"/>
        <child link="white_back_right"/>
        <origin xyz="-.20581 -.3837 0.51" rpy="0 0 ${pi/4}"/>
    </joint>

    <!-- ******************* Sensors *********************** -->

</robot>
