name: Tests

on: [push, pull_request, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
      # Pass the file to the action
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: /tmp/deps.repos
    if: always()