name: Tests

on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: humble 
          skip-tests: True
    if: always()
  
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        message: 'fix format'
