name: Tests

on: [push, pull_request, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
      # Run the generator and output the results to a file.
      - run: |
          rosinstall_generator <package-name> --rosdistro <target-distro> \
          --deps-only --deps --upstream-development > /tmp/deps.repos
      # Pass the file to the action
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: roboracing-software
          target-ros2-distro: galactic
          vcs-repo-file-url: /tmp/deps.repos
    if: always()